[build]
  publish = "build"
  command = "bundle exec middleman build --verbose"

[[redirects]]
  from = "https://taskafe.netlify.com/*"
  to = "https://www.taskafe.com/:splat"
  status = 301
  force = true
